### ISSUE TITLE
last_four should be nullable

### ISSUE THREAD

**Issue by Thomasmuur** [getcandy/getcandy#323] opened 2022-06-19 07:17 UTC
- GetCandy version: dev-main
- Laravel Version: X
- PHP Version: 8.X
- Database Driver & Version: mysql

some payment providers (like mollie) don’t support last_four, instead of 0000 it should be nullable

**Comment by glennjacobs** [comment] 2022-06-19 07:38
Duplicate of #322, so closing.

**Closed** 2022-06-19 07:38 UTC
