### ISSUE TITLE
Hub error : Cannot read properties of null

### ISSUE THREAD

**Issue by yaser2490** [getcandy/getcandy#14] opened 2021-12-25 12:19 UTC
This error was occurring when i change product-type in create product page:

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'en')
    at livewire.js:13
    at Array.reduce (<anonymous>)
    at Component.value (livewire.js:13)
    at Component.value (livewire.js:13)
    at livewire.js:13
    at alpine.min.js:7
    at Array.forEach (<anonymous>)
    at alpine.min.js:7
    at valueMutated (alpine.min.js:7)
    at ae.set (alpine.min.js:7)

**Comment by glennjacobs** [comment] 2021-12-25 18:42
Duplicate of #4

**Closed** 2021-12-25 18:42 UTC
