### ISSUE TITLE
Cannot create Variants or add tags in 13.1

### ISSUE THREAD

**Issue by Xenovalis** [getcandy/getcandy#300] opened 2022-05-25 21:14 UTC
- GetCandy version: 13.1
- Laravel Version: 8.83.14
- PHP Version: 8.1
- Database Driver & Version: Pgsql, 12.11

### Expected Behaviour:

Variants and tags are added to the product.

### Actual Behaviour:

They are not added or created.
Gives the following error in the console:
```
cdn.min.js:1 Alpine Expression Error: Pond is not defined

Expression: "Pond.removeFiles()"
```

No error in laravel.log

### Steps To Reproduce:

Try creating a variant or adding a tag in 13.1

**Comment by ryanmitchell** [comment] 2022-05-31 11:52
Did you republish the hub assets - `php artisan getcandy:hub:install` ?

**Comment by Xenovalis** [comment] 2022-05-31 19:21
I have done this, I've also deleted the files, made sure the style and JS didn't load, then republished them again and still got the same error.

**Comment by johnnywo** [comment] 2022-06-06 09:59
Hi! I have the same issue on a fresh install of 
current Laravel 9.16 Version, 
and current GetCandy 2.0-beta13.1 Version.
(PHP 8.1)

On saving product with created variant in Firefox Developer Edition console:

```
Alpine Expression Error: Pond is not defined
Expression: "Pond.removeFiles()"
```

```
<div x-data="" x-on:remove-images.window="Pond.removeFiles()" x-init="
    FilePond.registerPlugin(FilePondPluginImagePreview)
    FilePond.registerPlugin(FilePondPluginFileValidateSize)
    FilePond.registerPlugin(FilePondPluginFileValidateType);


    let Pond = FilePond.create($refs.input, {
      acceptedFileTypes:  [&quot;image\/*&quot;] ,
      imagePreviewHeight: 100,
      maxFileSize: 'Number(512000) * 1000',
      allowMultiple: true,
      onprocessfile: (error, file) => {
        if (!error) {
          Pond.removeFile(file.id)
        }
      },
      server: {
          process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => {
              window.livewire.find('Jlmo2Dhwg3uWwn1xN76M').upload('imageUploadQueue', file, load, error, progress)
          },
          revert: (filename, load) => {
              window.livewire.find('Jlmo2Dhwg3uWwn1xN76M').removeUpload('imageUploadQueue', filename, load)
          },
      },
    })

    this.addEventListener('pondReset', e => {
      Pond.removeFiles();
    });
  " wire:ignore="">
  <div class="filepond--root filepond--hopper" data-style-button-remove-item-position="left" data-style-button-process-item-position="right" data-style-load-indicator-position="right" data-style-progress-indicator-position="right" data-style-button-remove-item-align="false" style="height: 76px;"><input class="filepond--browser" type="file" id="filepond--browser-ulymgffgs" name="filepond" aria-controls="filepond--assistant-ulymgffgs" aria-labelledby="filepond--drop-label-ulymgffgs" accept="image/*" multiple=""><a class="filepond--credits" aria-hidden="true" href="https://pqina.nl/" target="_blank" rel="noopener noreferrer" style="transform: translateY(68px);">Powered by PQINA</a><div class="filepond--drop-label" style="transform: translate3d(0px, 0px, 0px); opacity: 1;"><label for="filepond--browser-ulymgffgs" id="filepond--drop-label-ulymgffgs" aria-hidden="true">Drag &amp; Drop your files or <span class="filepond--label-action" tabindex="0">Browse</span></label></div><div class="filepond--list-scroller" style="transform: translate3d(0px, 60px, 0px);"><ul class="filepond--list" role="list"></ul></div><div class="filepond--panel filepond--panel-root" data-scalable="true"><div class="filepond--panel-top filepond--panel-root"></div><div class="filepond--panel-center filepond--panel-root" style="transform: translate3d(0px, 8px, 0px) scale3d(1, 0.6, 1);"></div><div class="filepond--panel-bottom filepond--panel-root" style="transform: translate3d(0px, 68px, 0px);"></div></div><span class="filepond--assistant" id="filepond--assistant-ulymgffgs" role="status" aria-live="polite" aria-relevant="additions"></span><div class="filepond--drip"></div><fieldset class="filepond--data"></fieldset></div>
</div>
```
 
**Variant is not persisted to db and does not appear in admin hub product view.**

Thank you!!!
Emil

**Comment by Xenovalis** [comment] 2022-06-08 20:47
Video of me trying to add a variant
https://youtu.be/fLtg-Luisac

I made the same edit to `fileupload.php` as was done in #313 
It got rid of the error in console but it doesn't fix the issue of not being able to create variants.
Still no error in `laravel.log`

**Comment by johnnywo** [comment] 2022-06-09 05:23
Yes, same here. After some time trying to find out how that works I recognized that after clicking the "save Product" Button, when you do a page refresh in browser, the variants appear as expected..

**Comment by johnnywo** [comment] 2022-06-09 05:59
is there something with dispatching the job to the queue (I have a local redis installed, forgot to run queue:work command, wondered why no variants appeared, did run queue:work, variants where created. Then i tried to set the QUEUE_CONNECTION from _redis_ to standard _sync_ and right after making the process of creating a product with variants and clicking the save button, the variants appeared immediately as expected..)

**Comment by alecritson** [comment] 2022-06-09 12:26
Strange, the job should dispatch immediately regardless.

I still cannot reproduce this locally, I feel like I've tried quite a few different approaches too.

Might be something I need to pair with @glennjacobs to try and get something reproducible

**Comment by Xenovalis** [comment] 2022-06-09 16:45
Reinstalled `beanstalkd` and it fixed my queues and now I'm getting variants so I'm guessing it was just something with my queue workers. Thanks @johnnywo for making me check on my queue worker.

**Comment by johnnywo** [comment] 2022-06-10 05:39
@Xenovalis, you are welcome! So in summary I guess the topic of `Alpine Expression Error: Pond is not defined` has nothing to do with this behavior of variants getting not created. 
Thanks anyway to the creators and contributors of this promising package!

**Comment by alecritson** [comment] 2022-06-10 06:44
I'm going to close this issue as it seems to be resolved in the next release. :)

**Closed by alecritson** 2022-06-10 06:44 UTC
